#' A Bayesian Model Averaging package
#' 
#' Object of class \code{BMA} are created by the \code{fitBMA} functions
#'
#' 
#' An object of the class `BMA' has the following slots:
#' \itemize{
#' \item \code{coef} A matrix of coefficients generated by all variable combinations
#' \item \code{Rsquare} A vector of R-square values from the regressions
#' \item \code{postProb} A vector of posterior probabilities
#' \item \code{postModel} A vector of posterior models
#' \item \code{postExp} A vector of posterior expectations for coefficients
#' \item \code{x} The first input: A matrix of standardized covariates
#' \item \code{y} The second input: A numeric vector length of the number of regressions using variable combinations 
#' }
#'
#' @author Elif Ozdemir: \email{eozdemir@@wustl.edu}
#' @aliases BMA-class initialize,BMA-method getBMA,BMA-method 
#' @rdname BMA
#' @export
setClass(Class="BMA", 
         representation = representation(
           coef = "matrix",
           Rsquare = "numeric",
           postProb= "numeric",
           postModel= "numeric",
           postExp= "numeric",
           x = "matrix",
           y = "numeric"
         ),
         prototype = prototype(
           coef = matrix(),
           Rsquare = numeric(),
           postProb= numeric(),
           postModel= numeric(),
           postExp= numeric(),
           x = matrix(),
           y = numeric()
         )
)

#' @export
setMethod("initialize", "BMA", 
          function(.Object, coef=matrix(0), Rsquare=numeric(0), x=matrix(0), y=numeric(0), postProb=numeric(0), postModel=numeric(0), postExp=numeric(0)){
            .Object@coef<- coef
            .Object@Rsquare<- Rsquare
            .Object@postProb<- postProb
            .Object@postModel<- postModel
            .Object@postExp<- postExp
            .Object@x<- x
            .Object@y<- y
            .Object
          }
) 

#' @rdname BMA
#' @export 
setGeneric("getBMA",
           function(object="BMA"){
             standardGeneric("getBMA")
           }
)

#' @export
setMethod("getBMA", "BMA",
          function(object){ 
            return(list(coef=object@coef,Rsquare=object@Rsquare, postProb=object@postProb, postModel=object@postModel, postExp=object@postExp))
          }
)
